environment:
  matrix:
    - PYTHON: "C:/Python36"

install:
  - "set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%"

  - "pip.exe install -e ."
  - "pip.exe install mock pytest pytest-cov"

build: false

test_script:
  - "pytest.exe --cov=httpreplay"
  - 'pip.exe install ".[mitmproxy]"'
  - "pytest.exe --cov=httpreplay --cov-append"
